[book]
title = "Cẩm nang Lập trình Thi đấu"
authors = ["Smol Lemon"]
description = "Cẩm nang Lập trình Thi đấu"
language = "vi"

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://codeberg.org/SmolLemon/SmolBook"
edit-url-template = "https://github.com/SmolLemon/SmolBook/edit/main/{path}"

[output.html.fold]
enable = true
level = 0

[output.html.search]
limit-results = 16

[output.html.print]
enable = false